### PR TITLE
SysFind's hotfix

### PR DESCRIPTION
**Pull request by dungwinux**
Fix wrong return directory when using `Sysfind();`

### CODE REVIEW

**Comment by cszach** [comment]
Yeah nice, it worked.

**Review by cszach — APPROVED** [review]

**Comment by cszach** [comment]
Ready to merge. MERGE!

**Comment by dungwinux** [comment]
ready to merge ?

**Comment by dungwinux** [comment]
Please don't delete branch

**Comment by dungwinux** [comment]
The branch still continue

**Comment by cszach** [comment]
Luckily for you, God created "Restore".

**Comment by dungwinux** [comment]
Do we need to make release ? it's 1.5.1 now

**Comment by cszach** [comment]
Then I will have to edit the whole freaking wiki.

**Pull request merged**
