### PR TITLE
Update website but that's it

### PR DESCRIPTION
**Pull request by cszach**
Update statistics

### CODE REVIEW

**Comment by cszach** [comment]
Wait!!!

**Comment by dungwinux** [comment]
is everything allright ?

**Comment by dungwinux** [comment]
You should do sync it

**Comment by cszach** [comment]
Yaa it's okay to merge now.

**Comment by dungwinux** [comment]
You should sync it better than update every release

**Comment by cszach** [comment]
Next time, I should update the website before merging any pull request. Like before merging `tester-upd` I should had updated the website.

**Comment by dungwinux** [comment]
You **should** do sync now

**Comment by cszach** [comment]
How?

**Comment by dungwinux** [comment]
Wait, We need to update to the latest version too. I'll do it.

**Review by dungwinux — APPROVED** [review]

**Pull request merged**
