### PR TITLE
Feat/open editor

### PR DESCRIPTION
**Pull request by dungwinux**

### CODE REVIEW

**Comment by cszach** [comment]
If you pulled, what to do?

**Comment by cszach** [comment]
I don't thing it would be appropriate to do it, unless it will solve later sophisticate situations.

**Comment by cszach** [comment]
Let me just finish this.

**Comment by dungwinux** [comment]
This branch will not merge till I finish the feature.

**Comment by cszach** [comment]
Hey, the parameter `-edit` works fine but `-e` is having a bit problem.  
`FileNotOpen` - What FPC says

**Comment by dungwinux** [comment]
I'm not sure about that since I'm not looking into your code right now

**Comment by cszach** [comment]
Yeah just tellin'

**Comment by cszach** [comment]
Tomorrow I have a Chemistry test but I am here sitting and working on FPConsole...WTF is wrong with my life...

**Comment by cszach** [comment]
I'm almost there, I figured out why I am having `FileNotOpen`.

**Comment by dungwinux** [comment]
Go prepare for it
Maybe I can help you

**Comment by cszach** [comment]
Go update Windows, I will fix my code.

**Comment by dungwinux** [comment]
No, they release it tomorrow. I can help you with Chem

**Comment by dungwinux** [comment]
Well, the source now can't be compiled.

**Comment by cszach** [comment]
Why? What did you do?

**Comment by cszach** [comment]
I put compiler directives there for Linux only so...Just wait I will update as soon as possible.

**Comment by cszach** [comment]
Right, I just moved `ReadDat` out of `Execute`.

**Comment by cszach** [comment]
YEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!! IT WORKED!!!!!!!!!!!!!!!

**Comment by cszach** [comment]
Now I can say that I am pretty much done with it.

**Comment by cszach** [comment]
I will optimize the source code this afternoon, and I will do more tests to test the program.

**Comment by cszach** [comment]
`-e` works fine, `-edit` works fine, `-ec` works fine, `--no-execute` works fine.

**Comment by cszach** [comment]
Last but not least, before editing the file, we need to check if the file exists. Many editors would create a new file if it doesn't, but I'm not sure about the case in which the parent directories don't even exist as well. I will implement this after home.

**Comment by dungwinux** [comment]
This pull request will move to new one since changing branch

**Comment by cszach** [comment]
:sob: :sob: :sob: :wave:

**Pull request closed without merging**
