### PR TITLE
Reformat website files

### PR DESCRIPTION
**Pull request by cszach**
Yaa fix indent and remove unnecessary credits.

### CODE REVIEW

**Comment by cszach** [comment]
Merge real quick I gotta work on the opening editor thing we were discussing about.

**Comment by cszach** [comment]
I don't branch new branches from this branch. :/

**Comment by dungwinux** [comment]
Ok

**Comment by dungwinux** [comment]
Seems fine

**Review by dungwinux — APPROVED** [review]

**Pull request merged**
