### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by dungwinux**

### CODE REVIEW

**Comment by cszach** [comment]
Wanna review?

**Comment by dungwinux** [comment]
I'm thinking of merging this with #23

**Comment by cszach** [comment]
Need to get it done so we can move on to C++.

**Comment by cszach** [comment]
Lots of C++ cool programs are waiting for us.

**Comment by cszach** [comment]
I can't wait to learn C++ seriously.

**Comment by dungwinux** [comment]
well, you're right

**Comment by dungwinux** [comment]
Leave a review then i will merge

**Review by cszach — APPROVED** [review]

**Pull request merged**
