### PR TITLE
Feat/open editor reset

### PR DESCRIPTION
**Pull request by dungwinux**
## Changelog

- Open defualt editor to edit source before compiling (`-fe`) (#13)
- Add execution time (#11)
- Code now can execute with custom parameters
- Add color
- Change Input Folder

### CODE REVIEW

**Review by cszach — APPROVED** [review]
Yeah, everything is fine.

**Comment by cszach** [comment]
Hmmm...if you haven't changed the source code since the color implementation then everything is fine.

**Comment by dungwinux** [comment]
I will let 15 mins to make sure nothing wrong

**Comment by cszach** [comment]
Why? What does leaving it for 15 minutes do?

**Comment by dungwinux** [comment]
Hey, is there any way to show directly commit, request number to website?

**Pull request merged**
